### ISSUE TITLE
Is emulation currently not possible?

### ISSUE THREAD

**Issue by soledo** [ORNL/cyberwheel#2]
I am a student from South Korea with a keen interest in penetration testing through virtualization and emulation.

After reading your paper with great interest, I have a question I'd like to ask. In the paper, you mention using Firewheel for emulation, and one of the reasons cited for this choice is that it's not open-source. This led me to anticipate that your research might provide an open-source emulation solution that others could use.

However, upon further investigation, I've found that Firewheel itself is not publicly available. This leaves me wondering: how can one implement this simulation as an emulator without access to Firewheel?

I would greatly appreciate any insights or guidance you could provide on this matter. Your work is truly inspiring, and I'm eager to learn more about how I might be able to replicate or adapt your methods for my own studies.

**Comment by chaulagaina** [comment]
At the moment, emulation is currently in development so it is not ready for public use yet. It is something that we are in the process of testing and using with firewheel. It is true that firewheel is not currently publicly available, so it would be difficult to use with the open-source nature of the simulator. We are looking into other possible emulation implementations for the purpose of open-sourcing, we'll update this repo with more information as we work it out. Thank you for reading our paper and checking out cyberwheel!

**Comment by soledo** [comment]
Thanks for the update. I'll keep an eye on this repo for future developments on the emulation implementation. Looking forward to seeing how it progresses.
