### ISSUE TITLE
ModuleNotFoundError: No module named 'cyberwheel'

### ISSUE THREAD

**Issue by MTaylor97** [ORNL/cyberwheel#4]
Hello, 

I'm a student trying to use the training with train_cyberwheel.py however I am getting the following error:

```
(venv) PS C:\Users\markt\Documents\CW\cyberwheel\cyberwheel> python3 train_cyberwheel.py
Traceback (most recent call last):
  File "C:\Users\markt\Documents\CW\cyberwheel\cyberwheel\train_cyberwheel.py", line 22, in <module>
    from cyberwheel.cyberwheel_envs.cyberwheel_dynamic import DynamicCyberwheel
ModuleNotFoundError: No module named 'cyberwheel'
(venv) PS C:\Users\markt\Documents\CW\cyberwheel\cyberwheel>
```

**Comment by MTaylor97** [comment]
it seems to manage importing cyberwheel and run if I move train_cyberwheel.py to the root directory of the project, is this the intended usage?

**Comment by ruipcf** [comment]
That makes sense. If the file is part of the package structure, you may need to move it outside of that folder or use relative imports, such as:

`from ..cyberwheel_envs.cyberwheel_dynamic import DynamicCyberwheel`

Alternatively, you could modify the system path using the sys library to ensure Python can locate the module.
